### PR TITLE
Update geodb.service.ts

### PR DESCRIPTION
**Pull request by draxvint**
.replace only replace the first match. And when the string containing two + then the server response with bad request.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thanks for the fix!

**Comment by draxvint** [comment]
Are you also updating the npm package?

**Comment by wirefreethought** [comment]
I will do so later today

**Comment by wirefreethought** [comment]
I decided it's worth updating the project to the latest angular before publishing. I will focus on that this week. Stay tuned.

**Comment by wirefreethought** [comment]
@polynar Your fix actually resulted in a Typescript compile error. I've fixed in the latest version  (5.0.0) and published on npm.

**Pull request merged**
